# Generated by Django 5.2.10 on 2026-01-25 19:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='uniq_participant_per_event_email',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='gfm_ticket_event_i_4cee1e_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AlterField(
            model_name='participant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Gezahlter Betrag in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ticket',
            field=models.OneToOneField(blank=True, db_column='ticket_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='gfm.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='gfm_ticket_event_i_8670ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket__isnull', True)), fields=('event', 'email'), name='uniq_no_ticket_participant_per_event_email'),
        ),
    ]
