# Generated by Django 5.2.10 on 2026-01-31 12:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfm', '0002_remove_participant_uniq_participant_per_event_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gezahlter Betrag in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
